### ISSUE TITLE
Add missing files

### ISSUE THREAD

**Issue by okaufmann** [zipme/redmine_lightbox#58]
Folder assets/stylesheets should contain this images:
* fancybox_loading.gif
* fancybox_loading@2x.gif
* fancybox_overlay.png
* fancybox_sprite.png
* fancybox_sprite@2x.png
* blank.gif

**Comment by thegcat** [comment]
See #59.

**Comment by okaufmann** [comment]
Haha lol this is 8 month ago :D

Anyway: sorry I forgot to close this issue as i fixed it for myself...

Thanks ;)
